### ISSUE TITLE
Dataref created in the aircraft

### ISSUE THREAD

**Issue by BlaineElMono** [XPlane11Saitek/plugin#1]
Hi
In the previous version of the pluging I had profiles that included dataref created in the aircraft.
I could assign them in sw.txt and they worked fine.
Now I migrated to the latest version of the pluging. But when I load them it crashes and the switch does not work.
__
Example
X-Trident 412
SW.TXT file of the previous version:
SWITCH -1 MAG_OFF ON set(dataref(412/special/remove_before_flight):=1)
SWITCH -1 MAG_RIGHT ON set(dataref(412/special/remove_before_flight):=0)
SWITCH -1 MAG_LEFT ON set(dataref(412/engine/switches/engine_start):=-1)
SWITCH -1 MAG_BOTH ON set(dataref(412/engine/switches/engine_start):=0)
SWITCH -1 ENG_START ON set(dataref(412/engine/switches/engine_start):=1)
It runs smoothly. This is shown in the LOG.TXT
SAITEK (4.3.0) INFO: SW CHECK START
SAITEK (4.3.0) INFO: SW CHECK BUTTON DONE
SAITEK (4.3.0) INFO: SW CHECK DONE
SAITEK (4.3.0) INFO: RADIO CHECK START
SAITEK (4.3.0) INFO: RADIO CHECK UP DONE
SAITEK (4.3.0) INFO: RADIO CHECK DONE
SAITEK (4.3.0) INFO: MULTI CHECK START
SAITEK (4.3.0) INFO: MULTI CHECK DONE
__
SW.TXT file for the latest version of the plugin:
SWITCH -1 MAG_OFF ON set(dataref(412/special/remove_before_flight):=1)
SWITCH -1 MAG_RIGHT ON set(dataref(412/special/remove_before_flight):=0)
SWITCH -1 MAG_LEFT ON set(dataref(412/engine/switches/engine_start):=-1)
SWITCH -1 MAG_BOTH ON set(dataref(412/engine/switches/engine_start):=0)
SWITCH -1 ENG_START ON set(dataref(412/engine/switches/engine_start):=1)
Error that appears in the LOG.TXT when it crashes:
Saitek(0.3.0) INFO: Loader management
Saitek(0.3.0) INFO: Loading file B412
Saitek(0.3.0) INFO: Loading file B412/sw
Saitek(0.3.0) INFO: Loading file B412/ap
Saitek(0.3.0) INFO: Loading file all/ap/ap
Saitek(0.3.0) INFO: Loading file all/ap/radio
Saitek(0.3.0) INFO: Loading file all/ap/item
Saitek(0.3.0) INFO: Loading file all/ap/mode
Saitek(0.3.0) INFO: Loading file all/ap/garmin/g430x2
Saitek(0.3.0) INFO: Loading file all/ap/audio
Saitek(0.3.0) INFO: Loading file B412/radio
Saitek(0.3.0) INFO: Loading file all/radio/item
Saitek(0.3.0) INFO: Loading file all/radio/mode
Saitek(0.3.0) INFO: MULTI0 Loading
Saitek(0.3.0) INFO: MULTI0 Download completion
Saitek(0.3.0) INFO: RADIO0 Loading
Saitek(0.3.0) INFO: RADIO0 Download completion
Saitek(0.3.0) INFO: SWITH0 Loading
Saitek(0.3.0) CRITICAL ERROR: XP11DataRef incorrect/unexpected [412/special/remove_before_flight]
Saitek(0.3.0) WARNING: LOAD ERROR[XP11DataRef incorrect/unexpected [412/special/remove_before_flight]]
__
Am I doing something wrong?
What advice can you give me?
Thanks

**Comment by malanyuk** [comment]
Thanks.

**Comment by malanyuk** [comment]
Im accept dataref names 
```
    std::regex regex("(sim|laminar|plugin)\\/(\\w\\/?)+");
```
https://github.com/XPlane11Saitek/plugin/blob/master/src/source/dataref.cpp
choise 
* sim
* plugin
* laminar

Thanks.
This is bad logic.
I will remove validation by names.

**Comment by malanyuk** [comment]
Building 0.3.2

**Comment by malanyuk** [comment]
https://github.com/XPlane11Saitek/plugin/releases/tag/v0.3.2(98a82abb)

**Comment by malanyuk** [comment]
Please use version 0.3.2 for fixed name.
