### ISSUE TITLE
Problem with Array

### ISSUE THREAD

**Issue by BlaineElMono** [XPlane11Saitek/plugin#2]
Hi
In my sw.txt file I have these lines of code:
SWITCH -1 MAG_OFF ON set(array(sim/cockpit2/switches/generic_lights_switch[1]):=1)
SWITCH -1 MAG_OFF OFF set(array(sim/cockpit2/switches/generic_lights_switch[1]):=0)
SWITCH -1 MAG_RIGHT ON set(array(sim/cockpit2/switches/generic_lights_switch[2]):=1)
SWITCH -1 MAG_RIGHT OFF set(array(sim/cockpit2/switches/generic_lights_switch[2]):=0)

When I activate them, only position 0 is modified.
Positions 1 and 2 are not changed to value 1, they remain at 0.
sim/cockpit2/switches/generic_lights_switch[1.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.]

It is not only in this dataref, I tried with others and the problem persists.

It also happens that if I use an array position equal or greater than 10 it does not load the panel.
The LOG.txt shows this error:
Saitek(0.3.0) INFO: Loader management
Saitek(0.3.0) INFO: Loading file B412
Saitek(0.3.0) INFO: Loading file B412/sw
Saitek(0.3.0) INFO: Loading file B412/ap
Saitek(0.3.0) INFO: Loading file all/ap/ap
Saitek(0.3.0) INFO: Loading file all/ap/radio
Saitek(0.3.0) INFO: Loading file all/ap/item
Saitek(0.3.0) INFO: Loading file all/ap/mode
Saitek(0.3.0) INFO: Loading file all/ap/garmin/g430x2
Saitek(0.3.0) INFO: Loading file all/ap/audio
Saitek(0.3.0) INFO: Loading file B412/radio
Saitek(0.3.0) INFO: Loading file all/radio/item
Saitek(0.3.0) INFO: Loading file all/radio/mode
Saitek(0.3.0) INFO: MULTI0 Loading
Saitek(0.3.0) INFO: MULTI0 Download completion
Saitek(0.3.0) INFO: RADIO0 Loading
Saitek(0.3.0) INFO: RADIO0 Download completion
Saitek(0.3.0) INFO: SWITH0 Loading
Saitek(0.3.0) CRITICAL ERROR: XP11Array attach incorrect name [sim/cockpit2/switches/generic_lights_switch[10]]
Saitek(0.3.0) WARNING: LOAD ERROR[XP11Array attach incorrect name [sim/cockpit2/switches/generic_lights_switch[10]]]

Regards

JJ

**Comment by malanyuk** [comment]
Thanks.
The task is taken to work.

**Comment by malanyuk** [comment]
Too many symbol )
```
< SWITCH -1 MAG_OFF ON set(array(sim/cockpit2/switches/generic_lights_switch[1]):=1)
< SWITCH -1 MAG_OFF OFF set(array(sim/cockpit2/switches/generic_lights_switch[1]):=0)
< SWITCH -1 MAG_RIGHT ON set(array(sim/cockpit2/switches/generic_lights_switch[2]):=1)
< SWITCH -1 MAG_RIGHT OFF set(array(sim/cockpit2/switches/generic_lights_switch[2]):=0)
< 
< 
---
> SWITCH -1 MAG_OFF ON set(array(sim/cockpit2/switches/generic_lights_switch[1]:=1)
> SWITCH -1 MAG_OFF OFF set(array(sim/cockpit2/switches/generic_lights_switch[1]:=0)
> SWITCH -1 MAG_RIGHT ON set(array(sim/cockpit2/switches/generic_lights_switch[2]:=1)
> SWITCH -1 MAG_RIGHT OFF set(array(sim/cockpit2/switches/generic_lights_switch[2]:=0)
```
Please use next configuration.
```
SWITCH -1 MAG_OFF ON set(array(sim/cockpit2/switches/generic_lights_switch[1]):=1)
SWITCH -1 MAG_OFF OFF set(array(sim/cockpit2/switches/generic_lights_switch[1]):=0)
SWITCH -1 MAG_RIGHT ON set(array(sim/cockpit2/switches/generic_lights_switch[2]):=1)
SWITCH -1 MAG_RIGHT OFF set(array(sim/cockpit2/switches/generic_lights_switch[2]):=0)
```

**Comment by malanyuk** [comment]
My first recomendation incorect.

**Comment by malanyuk** [comment]
Confirm bug.

**Comment by malanyuk** [comment]
incorect work with array

**Comment by malanyuk** [comment]
Found bug

**Comment by malanyuk** [comment]
Builded 0.3.1

**Comment by malanyuk** [comment]
https://github.com/XPlane11Saitek/plugin/releases/tag/v0.3.1

**Comment by malanyuk** [comment]
Please try the new version 0.3.1.
Thank you for your appeal.
Sorry. This is really my mistake.
I allowed an incorrect casting without full testing.

**Comment by BlaineElMono** [comment]
Thank you!
You are doing an excellent pluging :)

**Comment by BlaineElMono** [comment]
I tested it.
Now the value is correctly modified according to the position of the array.
It still fails when the array is 10 or greater than 10.

Example with array position greater than 10 in sw.txt:
SWITCH 0 MAG_OFF ON set(array(sim/cockpit2/switches/custom_slider_on[10]):=0.0)
SWITCH 0 MAG_RIGHT ON set(array(sim/cockpit2/switches/custom_slider_on[10]):=1.0)

Error in log.txt
Saitek(0.3.2) INFO: SWITH0 Loading
Saitek(0.3.2) CRITICAL ERROR: XP11Array attach incorrect name [sim/cockpit2/switches/custom_slider_on[10]]
Saitek(0.3.2) WARNING: LOAD ERROR[XP11Array attach incorrect name [sim/cockpit2/switches/custom_slider_on[10]]]

**Comment by malanyuk** [comment]
Confirm...

**Comment by malanyuk** [comment]
Im accept only 0..8  not more 8.

**Comment by malanyuk** [comment]
Bug found.

**Comment by malanyuk** [comment]
Binding 0.3.4
https://gitlab.com/xplane11saitek/plugin/-/merge_requests/9

**Comment by malanyuk** [comment]
https://github.com/XPlane11Saitek/plugin/releases/tag/v0.3.4(f0303fb4)

**Comment by malanyuk** [comment]
Released new version 0.3.4.

**Comment by BlaineElMono** [comment]
Now everything works perfectly.

Thank you very much for your time :)

**Comment by malanyuk** [comment]
Thank you for your bug report.
