### ISSUE TITLE
Multipanel knob send command twice

### ISSUE THREAD

**Issue by CyberGuerro** [XPlane11Saitek/plugin#6]
It seems that the knob send command (UP and DOWN) twice to XP.
I verified this through DatarefTool.
I experienced this with Zibo.
Attached my [ap.txt](https://github.com/XPlane11Saitek/plugin/files/9438043/ap.txt) config.

I suspect that the plugin doesn't consider that saitek has "stepped knobs" and when you turn the knob, it turns to next near step. Sometimes I have to turn the knob between two steps to get the increment/decrement the value only one unit

Probably there is the same issue for radio panel's knobs.

PS.
It would be very appreciated to have a little help/guide to configure the display (labels and lines position), because I'm no be able to correctly configure display in ALT and VS modes.

**Comment by CyberGuerro** [comment]
Any news??

**Comment by malanyuk** [comment]
Hi. Im sorry. I will  offline. In country "backout" and "war". No have internert and time for support project.
But  in you config 
Line 9 
MULTI -1 main[NAV] ON command(laminar/B738/autopilot/lnav_press)
LIne 10 
MULTI -1 main[NAV] ON command(laminar/B738/autopilot/vnav_press)

One action main[NAV]  and setup two action  
* vnav_press
* lnav_press

**Comment by CyberGuerro** [comment]
I'm sorry for your situation I know and I hope that will change, meanwhile  **I ask you to re-open this issue for future fix (when you will have time for this project)**.
Config is correct:  Button has to execute multiple command (in this case it has to enable vnav and lnav). the issue is about "stepped knob" (it increase/decrease value  twice) on all saitek devices (multi and radio), buttons works perfectly.
